trigger: none

pool:
  name: 'CppDemoPool'

variables:
  buildConfiguration: 'Release'
  buildDirectory: 'build'

steps:

- checkout: self

- script: |
     rm -rf $(buildDirectory)
  displayName: "Clean Priovous Buil"

- script: |
     cppcheck --enable=all --suppress=missingIncludeSystem --xml --xml-version=2 .
  displayName: 'Run Cppcheck (Static Code Analysis)'

- script: |
     mkdir -p $(buildDirectory)
     cd $(buildDirectory)
     cmake .. -DCMAKE_BUILD_TYPE=$(buildConfiguration)
     cmake --build . --config $(buildConfiguration)
  displayName: 'CMake Clean and Build'

- script: |
     cd $(buildDirectory)
     ctest --output-on-failure
  displayName: 'Run unit testing'

- script: |
     lcov --capture --directory . --output-file coverage.info
     lcov --remove coverage.info '/usr/*' '*/test/*' '*/googletest/*' --output-file coverage_filtered.info
     genhtml coverage_filtered.info --output-directory coverage_report
  displayName: 'Generate Code Coverage Report'

- script: |
     ./$(buildDirectory)/hello_world
  displayName: 'Run Hello World'

- task: PublishBuildArtifacts@1
  inputs:
     pathtoPublish: '$(Build.SourcesDirectory)/coverage_report'
     artifactName: 'coverage_report'
     publishLocation: 'Container'
  displayName: 'Publish Code Coverage Report'
