trigger: none

pool:
  name: 'CppDemoPool'

variables:
  buildConfiguration: 'Coverage'
  buildDirectory: 'build'
  dockerImageName: 'balaji8421/cppapplication'

steps:

- checkout: self

- script: |
     rm -rf $(buildDirectory)
  displayName: "Clean Priovous Buil"

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykconnection'
    testType: 'code'
    failOnIssues: false
    projectName: '$(Build.Repository.Name)'

- script: |
     cppcheck --enable=all --suppress=missingIncludeSystem --xml --xml-version=2 . >cppcheck_report.xml
  displayName: 'Run Cppcheck (Static Code Analysis)'

- script: |
      cppcheck-htmlreport --file=cppcheck_report.xml --report-dir=cppcheck_report --source-dir=.
  displayName: 'Generate Cppcheck HTML Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cppcheck_report'
    ArtifactName: 'CppcheckReport'
    publishLocation: 'Container'
  displayName: 'Publish Cppcheck Report'

- script: |
     mkdir -p $(buildDirectory)
     cd $(buildDirectory)
     cmake .. -DCMAKE_BUILD_TYPE=$(buildConfiguration)
     cmake --build . --config $(buildConfiguration)
  displayName: 'CMake Clean and Build'

- script: |
     cd $(buildDirectory)
     ctest --output-on-failure
  displayName: 'Run unit testing'

- script: |
     lcov --capture --directory $(buildDirectory) --output-file coverage.info
     lcov --remove coverage.info '/usr/*' '*/test/*' '*/googletest/*' --output-file coverage_filtered.info
     genhtml coverage_filtered.info --output-directory coverage_report
  displayName: 'Generate Code Coverage Report'

- task: PublishBuildArtifacts@1
  inputs:
     pathtoPublish: '$(Build.SourcesDirectory)/coverage_report'
     artifactName: 'coverage_report'
     publishLocation: 'Container'
  displayName: 'Publish Code Coverage Report'

- task: Docker@2
  condition: succeeded()
  inputs:
    containerRegistry: 'cppapplication'
    repository: '$(dockerImageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: 'latest'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykconnection'
    testType: 'container'
    dockerImageName: 'balaji8421/cppapplication'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: false

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-connection'
    namespace: 'default'
    command: 'apply'
    arguments: '-f k8s/deployment.yaml -f k8s/service.yaml'