trigger: none

pool:
  name: 'CppDemoPool'

variables:
  buildConfiguration: 'Coverage'
  buildDirectory: 'build'
  dockerImageName: 'balaji8421/cppapplication'

steps:

- checkout: self

- script: |
     rm -rf $(buildDirectory)
  displayName: "Clean Priovous Buil"

- script: |
     cppcheck --enable=all --suppress=missingIncludeSystem --xml --xml-version=2 .
  displayName: 'Run Cppcheck (Static Code Analysis)'

- script: |
     mkdir -p $(buildDirectory)
     cd $(buildDirectory)
     cmake .. -DCMAKE_BUILD_TYPE=$(buildConfiguration)
     cmake --build . --config $(buildConfiguration)
  displayName: 'CMake Clean and Build'

- script: |
     cd $(buildDirectory)
     ctest --output-on-failure
  displayName: 'Run unit testing'

- script: |
     lcov --capture --directory $(buildDirectory) --output-file coverage.info
     lcov --remove coverage.info '/usr/*' '*/test/*' '*/googletest/*' --output-file coverage_filtered.info
     genhtml coverage_filtered.info --output-directory coverage_report
  displayName: 'Generate Code Coverage Report'

- task: PublishBuildArtifacts@1
  inputs:
     pathtoPublish: '$(Build.SourcesDirectory)/coverage_report'
     artifactName: 'coverage_report'
     publishLocation: 'Container'
  displayName: 'Publish Code Coverage Report'

- task: Docker@2
  condition: succeeded()
  inputs:
    containerRegistry: 'cppapplication'
    repository: '$(dockerImageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm $(dockerImageName):$(Build.BuildId)
  condition: succeeded()
  displayName: 'Run Docker Image'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-connection'
    namespace: 'default'
    command: 'apply'
    arguments: '-f k8s/deployment.yaml -f k8s/service.yaml'