apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cppapplication
  template:
    metadata:
      labels:
        app: cppapplication
    spec:
      containers:
      - name: cpp-app-container
        image: balaji8421/cppapplication:latest  # Pulling Docker Hub image from dockerhub registry
        resources:
          requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 8080